SELECT * FROM customers
LIMIT 10;

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender, 
	SUM(purchase_amount) AS total_revenue 
FROM customers
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than average purchase amount?
SELECT customer_id, 
	   purchase_amount
FROM customers
WHERE discount_applied='Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM customers);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
	   ROUND(AVG(review_rating), 2) AS avg_rating
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, 
	   ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customers
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscriber and non-subscribers.
SELECT subscription_status,
	   COUNT(*) AS total_customers,
	   ROUND(AVG(purchase_amount),2) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
	   ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100, 2) AS discount_rate
FROM customers
group by item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
WITH customer_type AS (
	SELECT customer_id, 
		   CASE WHEN previous_purchases = 1 THEN 'New'
				WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
				ELSE 'Loyal'
		   END AS customer_segment
	FROM customers
)
SELECT customer_segment, 
	   COUNT(*) AS total_customers 
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT item_purchased,
	   category,
	   COUNT(customer_id) AS total_orders,
       ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS product_rank
FROM customers
GROUP BY item_purchased, category
)
SELECT item_purchased, 
	   category,
       total_orders,
       product_rank
FROM item_counts
WHERE product_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
	   COUNT(customer_id) AS total_customers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT age_group, 
	   SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_groupcustomerscustomerscustomers
ORDER BY total_revenue DESC;